services:

  fastapi:
    build:
      context: ..
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    # Stage 2 und Stage 3 parallel starten
    command: bash -c "npm run stage2 &>/tmp/stage2.log & sleep 2 && python3 yaml_to_json.py && python3 main.py"
